export default {
    THEME_CHANGE: 'THEME_CHANGE',
    THEME_INIT: 'THEME_INIT',
    POPULAR_REFRESH: 'POPULAR_REFRESH',
    POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
    POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
    POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
    POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
    LANGUAGE_LOAD_SUCCESS: "LANGUAGE_LOAD_SUCCESS",
    FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",
}